package Controllers.Members;

import Controllers.LayoutController;
import DAO.MembreDAO;
import Models.amine.Personnel.Membre;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;

public class AddMemberController {

    @FXML private TextField tfNom;
    @FXML private TextField tfPrenom;
    @FXML private TextField tfEmail;
    @FXML private TextField tfPhone;

    private final MembreDAO membreDAO = new MembreDAO();

    @FXML
    public void saveMember() {
        Membre newMember = new Membre(
                0, // ID auto-generated by DB
                tfNom.getText(),
                tfPrenom.getText(),
                tfEmail.getText(),
                tfPhone.getText()
        );

        membreDAO.ajouterMembre(newMember);

        LayoutController.getInstance().loadView("/Views/Members/Members.fxml");
    }

    @FXML
    public void cancel() {
        LayoutController.getInstance().loadView("/Views/Members/Members.fxml");
    }
}
